name: file_lock
description: lock file prevent program start multiple times
version: 1.0.0
homepage: https://github.com/rmw-dart/file_lock

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  on_exit: ^1.0.0


